<?php

/* Note: This is a testing entry point not to be used production wise.
 * Do not edit this file manually! Use a dedicated
 * 'BlueSpiceDistribution.local.php' file if you wish to change the
 * settings. You should copy 'BlueSpiceDistribution.default.php' as a
 * starting point
 */

if ( file_exists( __DIR__ . '/BlueSpiceDistribution.local.php' ) ) {
	require_once __DIR__ . '/BlueSpiceDistribution.local.php';
} else {
	require_once __DIR__ . '/BlueSpiceDistribution.default.php';
}
